version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    volumes:
      - ./src:/usr/src/app/src
    command: "npm run start:dev"
    ports:
    - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx.dockerfile
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"