version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    volumes:
      #      TODO change implementation of file storage so that the assets are uploaded to google cloud storage or
      #      similar and not to filesystem of doker-compose
      - ./src:/usr/src/app/src
      - ./public/uploads:/usr/src/app/public/uploads
    command: "npm run start:dev"
    ports:
      - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx.dockerfile
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf
      - ./public/assets:/var/www/public/assets
    ports:
      - "8030:80"